---
- hosts: server foreman-proxy-content
  become: true
  roles:
    - role: foreman_proxy_devel
  vars:
    proxy_url: "https://github.com/stephen-nelsonjr/smart_proxy_example"
  tasks:
    - name: 'Clone Proxy'
      git:
        repo: "{{ proxy_url }}"
        dest: './'