---
- hosts: server foreman-proxy-content
  become: true
  roles:
    - role: foreman
    - role: foreman_proxy_content
    - role: foreman_installer
      foreman_installer_scenario: foreman-proxy-content
      foreman_installer_options_internal_use_only:
        - '--disable-system-checks'
        - '--certs-tar-file "{{ foreman_proxy_content_certs_tar }}"'
        - '--foreman-proxy-content-enable-ostree true'
        - '--foreman-proxy-trusted-hosts "{{ server_fqdn.stdout }}"'
        - '--foreman-proxy-trusted-hosts "{{ ansible_nodename }}"'
        - '--foreman-proxy-foreman-base-url "https://{{ server_fqdn.stdout }}"'
        - '--foreman-proxy-register-in-foreman true'
        - '--foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key.stdout }}"'
        - '--foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret.stdout }}"'
        - '--foreman-proxy-content-certs-tar "{{ foreman_proxy_content_certs_tar }}"'
        - '--foreman-proxy-content-parent-fqdn "{{ server_fqdn.stdout }}"'
        - '--puppet-server-foreman-url https://"{{ server_fqdn.stdout }}"'
  vars:
    proxy_url: "https://github.com/stephen-nelsonjr/smart_proxy_example"
  tasks:
    - name: 'Clone Proxy'
      git:
        repo: "{{ proxy_url }}"
        dest: './'